name: Batman
main: com.xxyrana.batman.Batman
version: 1.6
commands:
   test:
      description: Tests
      usage: /<command>
      permission: batman.test
      permission-message: You don't have <permission>
permissions:
    batman.be:
        description: Allows players to be Batman
        default: true
    batman.test:
        description: Allows players to test Batman status
        default: op